version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - dnf module install nodejs:12
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Testing...
      - yarn test
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
